---
kind: pipeline
type: docker
name: default

steps:
  - name: Run pre-commit
    image: flaudisio/pre-commit:latest
    commands:
      - pre-commit --version
      - pre-commit run --all-files --verbose --color always
