---
kind: pipeline
type: docker
name: default

steps:
  - name: Run pre-commit
    image: flaudisio/pre-commit:latest
    commands:
      - pre-commit --version
      - pre-commit run --all-files --verbose --color always

  - name: Build site
    image: flaudisio/mkdocs:1
    commands:
      - mkdocs --version
      - mkdocs build --clean --strict
